
import Customer.Customer;
import Customer.Insurance;
import Customer.Payment;
import DBconnect.Evidence_DBConnect;
import Exceptions.EmptyFieldException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hudek
 */
public class Evidence extends javax.swing.JFrame {

    private Evidence_DBConnect e_DBCon;
    /**
     * Creates new form Evidence
     */
    public Evidence() {
        initComponents();
        this.e_DBCon = new Evidence_DBConnect();
        getCustommers();
    }

    private void disableButtons(){
        edit_jButton2.setEnabled(false);
        delete_jButton1.setEnabled(false);
    }
    private void getPayments(){
        int ID = Integer.parseInt(ID_payments_jLabel27.getText());
        LinkedList<Payment> payments = this.e_DBCon.getPayment(ID);
        Object [] column_name = {"Payment (€)", "Date", "Note"};
        DefaultTableModel model = new DefaultTableModel(){
           
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        
        
        model.setColumnIdentifiers(column_name);
        model.setColumnCount(3);
        Object [] row = new Object[3];
        int num_rows =0;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        for (Payment payment : payments){
            String note = payment.getNote();
            Date date = payment.getDate();         
            String d= dateFormat.format(date);
            double paymentAmount  = payment.getPayment();
            row[0] = paymentAmount;
            row[1] = d;         
            row[2] = note;
            num_rows++;
            model.addRow(row);
           
        }
        model.setRowCount(num_rows);   
        jTable2.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
    Set customers to the table
    */
    private void getCustommers(){
            
        Object [] column_name = {"ID","First name", "Last Name", "Address", "Contract date", "Contract lenght", "Amount insured", "Insurance type"};
        DefaultTableModel model = new DefaultTableModel()  {
           
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        
        model.setColumnIdentifiers(column_name);
        model.setColumnCount(8);
        
        Object [] row = new Object[8];
    
        LinkedList<Customer> customers = this.e_DBCon.getCustomers();
        int num_rows =0;
        for (Customer customer : customers){
            int ID = customer.getID();
            String firstName = customer.getFirstName();
            String lastName = customer.getLastName();
            String address  = customer.getAddres();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
            Date date_of_contract = customer.getContractDate();
            String d = dateFormat.format(date_of_contract);
            int duration_of_contract  = customer.getContractLength();
            double amount_insured  = customer.getAmountInsured();
            String insurence_type  = customer.getInsuranceType().name();
            
            row[0] = ID;
            row[1] = firstName;
            row[2] = lastName;
            row[3] = address;
            row[4] = d;
            row[5] = duration_of_contract;
            row[6] = amount_insured;
            row[7] = insurence_type;
            num_rows++;
            model.addRow(row);
           
        }
        model.setRowCount(num_rows);    
        jTable1.setModel(model);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPaymentjFrame1 = new javax.swing.JFrame();
        add_paymentjButton9 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        canceljButton10 = new javax.swing.JButton();
        payment_jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        warning_jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        note_jTextArea1 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        first_namejLabel20 = new javax.swing.JLabel();
        last_namejLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ID_add_paymentsjLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        PaymentsJFrame = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        first_namejLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        last_namejLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ID_payments_jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Edit_custommer_jFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        First_name_edit_jTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Last_name_edit_jTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        address_edit_jTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contract_Length_edit_TextField4 = new javax.swing.JTextField();
        Contract_date_jLabel = new javax.swing.JLabel();
        Contract_lengt_jLabel = new javax.swing.JLabel();
        editjButton6 = new javax.swing.JButton();
        cancelEditjButton7 = new javax.swing.JButton();
        dateChooser_edit_Combo1 = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        amoundInsured_edit_jTextField1 = new javax.swing.JTextField();
        warning_jLabel7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        InsuranceType_edit_jComboBox1 = new javax.swing.JComboBox<>();
        Add_custommer_jFrame = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        First_name_jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Last_name_jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        address_jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        contract_Length_TextField5 = new javax.swing.JTextField();
        Contract_date_jLabel1 = new javax.swing.JLabel();
        Contract_lengt_jLabel1 = new javax.swing.JLabel();
        addjButton8 = new javax.swing.JButton();
        canceljButton9 = new javax.swing.JButton();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jLabel14 = new javax.swing.JLabel();
        amoundInsured_jTextField2 = new javax.swing.JTextField();
        warning_jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        InsuranceTypejComboBox2 = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        customerDetailsjPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        delete_jButton1 = new javax.swing.JButton();
        edit_jButton2 = new javax.swing.JButton();
        add_jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        addPaymentjFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addPaymentjFrame1.setTitle("Add payment");
        addPaymentjFrame1.setAlwaysOnTop(true);
        addPaymentjFrame1.setSize(new java.awt.Dimension(450, 400));
        addPaymentjFrame1.setType(java.awt.Window.Type.POPUP);
        addPaymentjFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                addPaymentjFrame1WindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                addPaymentjFrame1WindowClosed(evt);
            }
        });

        add_paymentjButton9.setText("Add payment");
        add_paymentjButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_paymentjButton9ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Add payment:");

        canceljButton10.setText("Cancel");
        canceljButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButton10ActionPerformed(evt);
            }
        });

        payment_jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_jTextField2ActionPerformed(evt);
            }
        });

        jLabel22.setText("Payment:");

        jLabel24.setText("Note:");

        warning_jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warning_jLabel9.setForeground(new java.awt.Color(255, 0, 0));

        note_jTextArea1.setColumns(20);
        note_jTextArea1.setRows(5);
        jScrollPane3.setViewportView(note_jTextArea1);

        jLabel26.setText("€");

        jLabel18.setText("First name:");

        jLabel19.setText("Last name:");

        jLabel27.setText("ID:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Customer:");

        javax.swing.GroupLayout addPaymentjFrame1Layout = new javax.swing.GroupLayout(addPaymentjFrame1.getContentPane());
        addPaymentjFrame1.getContentPane().setLayout(addPaymentjFrame1Layout);
        addPaymentjFrame1Layout.setHorizontalGroup(
            addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPaymentjFrame1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPaymentjFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(37, 37, 37)
                        .addComponent(warning_jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel29)
                    .addGroup(addPaymentjFrame1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addGroup(addPaymentjFrame1Layout.createSequentialGroup()
                                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel27))
                                .addGap(29, 29, 29)
                                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(last_namejLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(first_namejLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ID_add_paymentsjLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addPaymentjFrame1Layout.createSequentialGroup()
                                        .addComponent(payment_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(addPaymentjFrame1Layout.createSequentialGroup()
                                            .addComponent(add_paymentjButton9)
                                            .addGap(18, 18, 18)
                                            .addComponent(canceljButton10))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        addPaymentjFrame1Layout.setVerticalGroup(
            addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPaymentjFrame1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warning_jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(10, 10, 10)
                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(ID_add_paymentsjLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(first_namejLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(last_namejLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payment_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26))
                .addGap(11, 11, 11)
                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(35, 35, 35)
                .addGroup(addPaymentjFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceljButton10)
                    .addComponent(add_paymentjButton9))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        addPaymentjFrame1.getAccessibleContext().setAccessibleDescription("");
        addPaymentjFrame1.getAccessibleContext().setAccessibleParent(PaymentsJFrame);

        PaymentsJFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        PaymentsJFrame.setTitle("Payments");
        PaymentsJFrame.setType(java.awt.Window.Type.POPUP);
        PaymentsJFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                PaymentsJFrameWindowClosed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Payment", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setFocusable(false);
        jScrollPane2.setViewportView(jTable2);

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Payments:");

        jButton1.setText("Add payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel20.setText("First name:");

        jLabel23.setText("Last name:");

        jLabel25.setText("ID:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Customer:");

        javax.swing.GroupLayout PaymentsJFrameLayout = new javax.swing.GroupLayout(PaymentsJFrame.getContentPane());
        PaymentsJFrame.getContentPane().setLayout(PaymentsJFrameLayout);
        PaymentsJFrameLayout.setHorizontalGroup(
            PaymentsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentsJFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaymentsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaymentsJFrameLayout.createSequentialGroup()
                        .addGap(0, 709, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                    .addGroup(PaymentsJFrameLayout.createSequentialGroup()
                        .addGroup(PaymentsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel28)
                            .addGroup(PaymentsJFrameLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ID_payments_jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(first_namejLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(last_namejLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PaymentsJFrameLayout.setVerticalGroup(
            PaymentsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentsJFrameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PaymentsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(last_namejLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PaymentsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ID_payments_jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PaymentsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25))
                        .addComponent(first_namejLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaymentsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        Edit_custommer_jFrame.setTitle("Edit customer");
        Edit_custommer_jFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Edit_custommer_jFrame.setSize(new java.awt.Dimension(150, 150));
        Edit_custommer_jFrame.setType(java.awt.Window.Type.POPUP);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Edit customer:");

        First_name_edit_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_name_edit_jTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("First name:");

        Last_name_edit_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_name_edit_jTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name:");

        address_edit_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_edit_jTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Address:");

        Contract_date_jLabel.setText("Contract date:");
        Contract_date_jLabel.setMaximumSize(new java.awt.Dimension(77, 14));
        Contract_date_jLabel.setMinimumSize(new java.awt.Dimension(77, 14));
        Contract_date_jLabel.setPreferredSize(new java.awt.Dimension(77, 14));

        Contract_lengt_jLabel.setText("Contract length:");

        editjButton6.setText("Edit");
        editjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton6ActionPerformed(evt);
            }
        });

        cancelEditjButton7.setText("Cancel");
        cancelEditjButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditjButton7ActionPerformed(evt);
            }
        });

        jLabel6.setText("Amount insured:");

        warning_jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warning_jLabel7.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setText("€");

        jLabel8.setText("months");

        jLabel9.setText("Insurance type:");

        InsuranceType_edit_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIFE_INSURANCE", "TRAVEL_INSURANCE", "DISABILITY_INSURANCE", "HEALTH_INSURANCE", "UNKNOW", " " }));
        InsuranceType_edit_jComboBox1.setSelectedIndex(-1);
        InsuranceType_edit_jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsuranceType_edit_jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Edit_custommer_jFrameLayout = new javax.swing.GroupLayout(Edit_custommer_jFrame.getContentPane());
        Edit_custommer_jFrame.getContentPane().setLayout(Edit_custommer_jFrameLayout);
        Edit_custommer_jFrameLayout.setHorizontalGroup(
            Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Contract_date_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Contract_lengt_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                        .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooser_edit_Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_edit_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                                .addComponent(amoundInsured_edit_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(Last_name_edit_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                        .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InsuranceType_edit_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                                .addComponent(contract_Length_edit_TextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warning_jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                                .addComponent(First_name_edit_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Edit_custommer_jFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editjButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelEditjButton7)))
                .addContainerGap())
        );
        Edit_custommer_jFrameLayout.setVerticalGroup(
            Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Edit_custommer_jFrameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warning_jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_name_edit_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Last_name_edit_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address_edit_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contract_date_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooser_edit_Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(contract_Length_edit_TextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Contract_lengt_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(amoundInsured_edit_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(InsuranceType_edit_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Edit_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelEditjButton7)
                    .addComponent(editjButton6)))
        );

        Add_custommer_jFrame.setTitle("Add customer");
        Add_custommer_jFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Add_custommer_jFrame.setResizable(false);
        Add_custommer_jFrame.setSize(new java.awt.Dimension(150, 150));
        Add_custommer_jFrame.setType(java.awt.Window.Type.POPUP);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Add customer:");

        First_name_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_name_jTextField1ActionPerformed(evt);
            }
        });

        jLabel11.setText("First name:");

        Last_name_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_name_jTextField1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Last name:");

        address_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_jTextField1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Address:");

        contract_Length_TextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contract_Length_TextField5ActionPerformed(evt);
            }
        });

        Contract_date_jLabel1.setText("Contract date:");

        Contract_lengt_jLabel1.setText("Contract length:");

        addjButton8.setText("Add");
        addjButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton8ActionPerformed(evt);
            }
        });

        canceljButton9.setText("Cancel");
        canceljButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButton9ActionPerformed(evt);
            }
        });

        dateChooserCombo2.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    jLabel14.setText("Amount insured:");

    warning_jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    warning_jLabel8.setForeground(new java.awt.Color(255, 0, 0));

    jLabel15.setText("€");

    jLabel16.setText("months");

    jLabel17.setText("Insurance type:");
    jLabel17.setPreferredSize(new java.awt.Dimension(81, 14));

    InsuranceTypejComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIFE_INSURANCE", "TRAVEL_INSURANCE", "DISABILITY_INSURANCE", "HEALTH_INSURANCE", "UNKNOW", " " }));
    InsuranceTypejComboBox2.setSelectedIndex(-1);
    InsuranceTypejComboBox2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            InsuranceTypejComboBox2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout Add_custommer_jFrameLayout = new javax.swing.GroupLayout(Add_custommer_jFrame.getContentPane());
    Add_custommer_jFrame.getContentPane().setLayout(Add_custommer_jFrameLayout);
    Add_custommer_jFrameLayout.setHorizontalGroup(
        Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
                    .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
                            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Contract_date_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Last_name_jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(address_jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                .addComponent(First_name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
                            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(Contract_lengt_jLabel1)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
                                    .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(amoundInsured_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(InsuranceTypejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
                                    .addComponent(contract_Length_TextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel16)))))
                    .addGap(130, 130, 130))
                .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
                    .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_custommer_jFrameLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(addjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(canceljButton9))
                        .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(43, 43, 43)
                            .addComponent(warning_jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)))
                    .addContainerGap())))
    );
    Add_custommer_jFrameLayout.setVerticalGroup(
        Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Add_custommer_jFrameLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(warning_jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(First_name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(Last_name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(address_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(8, 8, 8)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(Contract_date_jLabel1)
                .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(contract_Length_TextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel16)
                .addComponent(Contract_lengt_jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(amoundInsured_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel15)
                .addComponent(jLabel14))
            .addGap(16, 16, 16)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(InsuranceTypejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
            .addGroup(Add_custommer_jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(canceljButton9)
                .addComponent(addjButton8)))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Evidence");

    jTabbedPane1.setToolTipText("Evidence");
    jTabbedPane1.setName("Evidance"); // NOI18N

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null}
        },
        new String [] {
            "ID", "First name", "Last name", "Addres", "Contract date", "Contract date", "Amound insured", "Insurence type"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
        public void mousePressed(java.awt.event.MouseEvent evt) {
            jTable1MousePressed(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    delete_jButton1.setText("Delete customer");
    delete_jButton1.setEnabled(false);
    delete_jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            delete_jButton1ActionPerformed(evt);
        }
    });

    edit_jButton2.setText("Edit customer");
    edit_jButton2.setEnabled(false);
    edit_jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            edit_jButton2ActionPerformed(evt);
        }
    });

    add_jButton3.setText("Add new customer");
    add_jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            add_jButton3ActionPerformed(evt);
        }
    });

    jButton4.setText("Exit");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jLabel30.setText("Doubleclick row to show payment details.");

    javax.swing.GroupLayout customerDetailsjPanel1Layout = new javax.swing.GroupLayout(customerDetailsjPanel1);
    customerDetailsjPanel1.setLayout(customerDetailsjPanel1Layout);
    customerDetailsjPanel1Layout.setHorizontalGroup(
        customerDetailsjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        .addGroup(customerDetailsjPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(add_jButton3)
            .addGap(18, 18, 18)
            .addComponent(edit_jButton2)
            .addGap(18, 18, 18)
            .addGroup(customerDetailsjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
        .addGroup(customerDetailsjPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel30)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    customerDetailsjPanel1Layout.setVerticalGroup(
        customerDetailsjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(customerDetailsjPanel1Layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel30)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
            .addGroup(customerDetailsjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(add_jButton3)
                .addComponent(edit_jButton2)
                .addComponent(delete_jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButton4)
            .addGap(6, 6, 6))
    );

    jTabbedPane1.addTab("Customers details", customerDetailsjPanel1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
    );

    jTabbedPane1.getAccessibleContext().setAccessibleName("Evidence");

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_jButton1ActionPerformed
        // TODO add your handling code here:
        int rowSelected= jTable1.getSelectedRow();
        int ID= (Integer)(jTable1.getValueAt(rowSelected, 0));
        disableButtons();
        e_DBCon.deleteCustomer(ID);      
        getCustommers();
        
    }//GEN-LAST:event_delete_jButton1ActionPerformed

    private void edit_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_jButton2ActionPerformed
        // TODO add your handling code here:
       this.Edit_custommer_jFrame.setSize(800,600);
       this.Edit_custommer_jFrame.setVisible(true);
       disableButtons();
    }//GEN-LAST:event_edit_jButton2ActionPerformed

    private void add_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_jButton3ActionPerformed
       this.Add_custommer_jFrame.setSize(800,600);
       this.Add_custommer_jFrame.setVisible(true);
       disableButtons();
    }//GEN-LAST:event_add_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.PaymentsJFrame.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void address_edit_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_edit_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_edit_jTextFieldActionPerformed

    private void cancelEditjButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditjButton7ActionPerformed
        this.Edit_custommer_jFrame.setVisible(false);
        warning_jLabel7.setText("");
    }//GEN-LAST:event_cancelEditjButton7ActionPerformed

    private void editjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton6ActionPerformed
        // TODO add your handling code here:
       try{
           if(First_name_edit_jTextField.getText().equals("")||
                Last_name_edit_jTextField.getText().equals("")||
                contract_Length_edit_TextField4.getText().equals("")||
                amoundInsured_edit_jTextField1.getText().equals("")||
                address_edit_jTextField.getText().equals(""))
            
                throw new EmptyFieldException("Empty fileds!");
           else {
            int rowSelected= jTable1.getSelectedRow();
            int ID= (Integer)(jTable1.getValueAt(rowSelected, 0));
            String insuranceType = (String)InsuranceType_edit_jComboBox1.getSelectedItem();
            Insurance insurnce;
            if(insuranceType==null)
                insurnce= Insurance.UNKNOW;
            else 
                 insurnce= Insurance.valueOf(insuranceType);
            
            String firstName= First_name_edit_jTextField.getText();
            String lastName= Last_name_edit_jTextField.getText();
            int contractDuration= Integer.parseInt(contract_Length_edit_TextField4.getText());
            double amoundInsured= Double.parseDouble(amoundInsured_edit_jTextField1.getText());
            String address = address_edit_jTextField.getText();
          
            
            DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
            Date date = df.parse(dateChooser_edit_Combo1.getText());
            
            Customer customer = new Customer(firstName, lastName, address, date, contractDuration, amoundInsured, insurnce);
           
            e_DBCon.updateCustomer(ID, customer);
            Edit_custommer_jFrame.dispose();
            resetEdit_custommer_jFrame1();
            getCustommers();
             }
       }
        catch (ParseException parseException) {
            System.out.println("Message1" + parseException.getMessage());
            warning_jLabel7.setText(parseException.getMessage());
        }
       catch (EmptyFieldException ex) {
            System.out.println("Message2" + ex.getMessage());
            warning_jLabel7.setText(ex.getMessage());
        }
       catch (NumberFormatException ex) {
            System.out.println("Message2" + ex.getMessage());
            warning_jLabel7.setText("Wrong format. Input number");
        }
       catch (Exception ex) {
            System.out.println("Message" + ex.getMessage());
            warning_jLabel7.setText(ex.getMessage());
        }
       
    }//GEN-LAST:event_editjButton6ActionPerformed

    private void resetAdd_custommer_jFrame1(){
                warning_jLabel8.setText("");
                First_name_jTextField1.setText("");
                Last_name_jTextField1.setText("");
                contract_Length_TextField5.setText("");
                amoundInsured_jTextField2.setText("");
                address_jTextField1.setText("");
                InsuranceTypejComboBox2.setSelectedIndex(-1);
        
    }
    private void resetEdit_custommer_jFrame1(){
                warning_jLabel7.setText("");
                First_name_edit_jTextField.setText("");
                Last_name_edit_jTextField.setText("");
                contract_Length_edit_TextField4.setText("");
                amoundInsured_edit_jTextField1.setText("");
                address_edit_jTextField.setText("");
                InsuranceType_edit_jComboBox1.setSelectedIndex(-1);           
        
    }
    private void resetAdd_Payment_jFrame1(){
                warning_jLabel9.setText("");
                payment_jTextField2.setText("");
                note_jTextArea1.setText("");
                
        
    }
    
    private void First_name_edit_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_name_edit_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_name_edit_jTextFieldActionPerformed

    private void InsuranceType_edit_jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsuranceType_edit_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsuranceType_edit_jComboBox1ActionPerformed

    private void Last_name_edit_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Last_name_edit_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_name_edit_jTextFieldActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        edit_jButton2.setEnabled(true);
        delete_jButton1.setEnabled(true);       
        JTable table =(JTable) evt.getSource();
         if (evt.getClickCount() == 2 && table.getSelectedRow() != -1) {
               this.PaymentsJFrame.setSize(800, 600);
               String firstName= (String)table.getValueAt(table.getSelectedRow(), 1);
               String lastName= (String)table.getValueAt(table.getSelectedRow(), 2);
               String ID = "" + table.getValueAt(table.getSelectedRow(), 0);
               first_namejLabel21.setText(firstName);
               last_namejLabel24.setText(lastName);
               ID_payments_jLabel27.setText(ID);
               getPayments();
               this.PaymentsJFrame.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void First_name_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_name_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_name_jTextField1ActionPerformed

    private void Last_name_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Last_name_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_name_jTextField1ActionPerformed

    private void address_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_jTextField1ActionPerformed

    private void addjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton8ActionPerformed
        // TODO add your handling code here:
         try{
           if(First_name_jTextField1.getText().equals("")||
                Last_name_jTextField1.getText().equals("")||
                contract_Length_TextField5.getText().equals("")||
                amoundInsured_jTextField2.getText().equals("")||
                address_jTextField1.getText().equals(""))
               
                throw new EmptyFieldException("Empty fileds!");
           else {
            String insuranceType = (String)InsuranceTypejComboBox2.getSelectedItem();
            Insurance insurnce;
            if(insuranceType==null)
                insurnce= Insurance.UNKNOW;
            else 
                 insurnce= Insurance.valueOf(insuranceType);
            
            String firstName= First_name_jTextField1.getText();
            String lastName= Last_name_jTextField1.getText();          
            int contractDuration= Integer.parseInt(contract_Length_TextField5.getText());
            double amoundInsured= Double.parseDouble(amoundInsured_jTextField2.getText());
            String address = address_jTextField1.getText();
          
            
            DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
            Date date = df.parse(dateChooserCombo2.getText());
            Customer customer = new Customer(firstName, lastName, address, date, contractDuration, amoundInsured, insurnce);
      
            e_DBCon.insertCustomer(customer);
            Add_custommer_jFrame.dispose();
            resetAdd_custommer_jFrame1();
            getCustommers();
             }
       }
        catch (ParseException parseException) {
            System.out.println("Message1" + parseException.getMessage());
            warning_jLabel8.setText(parseException.getMessage());
        }
       catch (EmptyFieldException ex) {
            System.out.println("Message2" + ex.getMessage());
            warning_jLabel8.setText(ex.getMessage());
        }
       catch (NumberFormatException ex) {
            System.out.println("Message2" + ex.getMessage());
            warning_jLabel8.setText("Wrong format. Input number");
        }
        catch (Exception ex) {
            System.out.println("Message" + ex.getMessage());
            warning_jLabel8.setText(ex.getMessage());
        }
    }//GEN-LAST:event_addjButton8ActionPerformed

    private void canceljButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButton9ActionPerformed
        // TODO add your handling code here:
          Add_custommer_jFrame.dispose();
        
    }//GEN-LAST:event_canceljButton9ActionPerformed

    private void InsuranceTypejComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsuranceTypejComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsuranceTypejComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String firstName= first_namejLabel21.getText();
        String lastName= last_namejLabel24.getText();
        String ID =  ID_payments_jLabel27.getText();
        first_namejLabel20.setText(firstName);
        last_namejLabel23.setText(lastName);
        ID_add_paymentsjLabel28.setText(ID);
        addPaymentjFrame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_paymentjButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_paymentjButton9ActionPerformed
        // TODO add your handling code here:
      try
      {
        double payment = Double.parseDouble(payment_jTextField2.getText());
        String note = note_jTextArea1.getText();
        if(payment_jTextField2.getText().equals("")|| note_jTextArea1.getText().equals(""))
            throw new EmptyFieldException("Empty fields!");
        int ID = Integer.parseInt(ID_payments_jLabel27.getText());
        e_DBCon.insertPayment(ID, payment, note); 
        addPaymentjFrame1.dispose();
        resetAdd_Payment_jFrame1();
        getPayments();
       }
        catch(EmptyFieldException ex){
            System.out.println("Message2" + ex.getMessage());
            warning_jLabel9.setText(ex.getMessage());
        }
      catch (NumberFormatException ex) {
            System.out.println("Message2" + ex.getMessage());
            warning_jLabel9.setText("Wrong format. Input number");
        }
        catch (Exception ex) {
            System.out.println("Message" + ex.getMessage());
            warning_jLabel9.setText(ex.getMessage());
        }
    }//GEN-LAST:event_add_paymentjButton9ActionPerformed

    private void canceljButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButton10ActionPerformed
        // TODO add your handling code here:
        addPaymentjFrame1.dispose();
    }//GEN-LAST:event_canceljButton10ActionPerformed

    private void payment_jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payment_jTextField2ActionPerformed

    private void contract_Length_TextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contract_Length_TextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contract_Length_TextField5ActionPerformed

    private void addPaymentjFrame1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addPaymentjFrame1WindowActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_addPaymentjFrame1WindowActivated

    private void addPaymentjFrame1WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addPaymentjFrame1WindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPaymentjFrame1WindowClosed

    private void PaymentsJFrameWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PaymentsJFrameWindowClosed
        // TODO add your handling code here:
        addPaymentjFrame1.dispose();
    }//GEN-LAST:event_PaymentsJFrameWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evidence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Add_custommer_jFrame;
    private javax.swing.JLabel Contract_date_jLabel;
    private javax.swing.JLabel Contract_date_jLabel1;
    private javax.swing.JLabel Contract_lengt_jLabel;
    private javax.swing.JLabel Contract_lengt_jLabel1;
    private javax.swing.JFrame Edit_custommer_jFrame;
    private javax.swing.JTextField First_name_edit_jTextField;
    private javax.swing.JTextField First_name_jTextField1;
    private javax.swing.JLabel ID_add_paymentsjLabel28;
    private javax.swing.JLabel ID_payments_jLabel27;
    private javax.swing.JComboBox<String> InsuranceType_edit_jComboBox1;
    private javax.swing.JComboBox<String> InsuranceTypejComboBox2;
    private javax.swing.JTextField Last_name_edit_jTextField;
    private javax.swing.JTextField Last_name_jTextField1;
    private javax.swing.JFrame PaymentsJFrame;
    private javax.swing.JFrame addPaymentjFrame1;
    private javax.swing.JButton add_jButton3;
    private javax.swing.JButton add_paymentjButton9;
    private javax.swing.JButton addjButton8;
    private javax.swing.JTextField address_edit_jTextField;
    private javax.swing.JTextField address_jTextField1;
    private javax.swing.JTextField amoundInsured_edit_jTextField1;
    private javax.swing.JTextField amoundInsured_jTextField2;
    private javax.swing.JButton cancelEditjButton7;
    private javax.swing.JButton canceljButton10;
    private javax.swing.JButton canceljButton9;
    private javax.swing.JTextField contract_Length_TextField5;
    private javax.swing.JTextField contract_Length_edit_TextField4;
    private javax.swing.JPanel customerDetailsjPanel1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserCombo dateChooser_edit_Combo1;
    private javax.swing.JButton delete_jButton1;
    private javax.swing.JButton edit_jButton2;
    private javax.swing.JButton editjButton6;
    private javax.swing.JLabel first_namejLabel20;
    private javax.swing.JLabel first_namejLabel21;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel last_namejLabel23;
    private javax.swing.JLabel last_namejLabel24;
    private javax.swing.JTextArea note_jTextArea1;
    private javax.swing.JTextField payment_jTextField2;
    private javax.swing.JLabel warning_jLabel7;
    private javax.swing.JLabel warning_jLabel8;
    private javax.swing.JLabel warning_jLabel9;
    // End of variables declaration//GEN-END:variables
}
